// <auto-generated />
using CodeFIrstDB.Properties.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFIrstDB.Migrations
{
    [DbContext(typeof(SchoolDBContext))]
    partial class SchoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.ClassCourse", b =>
                {
                    b.Property<int>("ClassCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassCourseID"));

                    b.Property<int>("ClassID_FK")
                        .HasColumnType("int");

                    b.Property<int>("CourseID_FK")
                        .HasColumnType("int");

                    b.HasKey("ClassCourseID");

                    b.HasIndex("ClassID_FK");

                    b.HasIndex("CourseID_FK");

                    b.ToTable("ClassCourses");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClassID_FK")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ClassID_FK");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.ClassCourse", b =>
                {
                    b.HasOne("CodeFIrstDB.Properties.Models.Class", "Class")
                        .WithMany("ClassCourses")
                        .HasForeignKey("ClassID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFIrstDB.Properties.Models.Course", "Course")
                        .WithMany("ClassCourses")
                        .HasForeignKey("CourseID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Student", b =>
                {
                    b.HasOne("CodeFIrstDB.Properties.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID_FK");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Class", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CodeFIrstDB.Properties.Models.Course", b =>
                {
                    b.Navigation("ClassCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
